-- ###############################
-- ## Project: MTA:Speedrace	##
-- ## Name: ChatBoxServer		##
-- ## Author: Noneatme			##
-- ## Version: 1.0				##
-- ## License: See top Folder	##
-- ###############################

-- FUNCTIONS / METHODS --

local cFunc = {};		-- Local Functions 
local cSetting = {};	-- Local Settings

ChatBoxServer = {};
ChatBoxServer.__index = ChatBoxServer;

--[[

]]

-- ///////////////////////////////
-- ///// New 				//////
-- ///////////////////////////////

function ChatBoxServer:New(...)
	local obj = setmetatable({}, {__index = self});
	if obj.Constructor then
		obj:Constructor(...);
	end
	return obj;
end


-- ///////////////////////////////
-- ///// SendText 			//////
-- ///////////////////////////////

function ChatBoxServer:SendText(group, text)
	local player = source;
	--text = string.gsub(getPlayerName(player), '#%x%x%x%x%x%x', '')..": "..text
	
	if(self:ContainsBadWords(text) == true) then
		text = self.randomSaetze[math.random(1, #self.randomSaetze)];
	end
	text = getPlayerName(player)..": "..text
		
	logger:OutputMySQL("Chat Message", "["..group.."]"..text);
		
	triggerClientEvent(getRootElement(), "ChatBox:SendTextBack", getRootElement(), group, text);

end

-- ///////////////////////////////
-- ///// SendCommand 		//////
-- ///////////////////////////////

function ChatBoxServer:SendCommand(cmd, params)
	local player = source;
	
	executeCommandHandler(cmd, player, unpack(params))
end


-- ///////////////////////////////
-- ///// ContainsBadWords   //////
-- ///////////////////////////////

function ChatBoxServer:ContainsBadWords(text)
	local new_val = string.lower(text);

	for index, val in pairs(self.insults) do
		if(string.find(new_val, string.lower(val), 0, true)) then
			return true;
		end
	end
	
	local last_byte;
	local warnings = 0;
	
	for i = 1, string.len(new_val), 1 do
		local newbyte = string.byte(new_val, i);
		if(newbyte == last_byte) then
			warnings = warnings+1;
		
			if(warnings == 5) then
				return true;
			end
		end
		last_byte = newbyte;
	end
	return false;
end

-- ///////////////////////////////
-- ///// Constructor 		//////
-- ///////////////////////////////

function ChatBoxServer:Constructor(...)
	self.sendTextFunc = function(...) self:SendText(...) end;
	self.sendCMDFunc = function(...) self:SendCommand(...) end;

	addEvent("ChatBox:SendText", true);
	addEvent("ChatBox:SendCommand", true);
	
	addEventHandler("ChatBox:SendText", getRootElement(), self.sendTextFunc);
	addEventHandler("ChatBox:SendCommand", getRootElement(), self.sendCMDFunc);
	--logger:OutputInfo("[CALLING] ChatBoxServer: Constructor");
	
	self.randomSaetze = {
		"I forgot my pills today!",
		"I'm a pink pig!",
		"I love my parents...",
		"I forgot my medicine!"
	}
	
	self.insults = {
		"Affenarsch",
		"Affenkotstück", 
		"Affenmensch", 
		"Allmachtsdackel", 
		"Ameisenficker", 
		"Analbaron", 
		"Analraupe", 
		"Analzone", 
		"anorektische Fettsau", 
		"Arschforscher", 
		"Arschfotzengesicht", 
		"Arschgesicht", 
		"Arschkeks", 
		"Arschkopf", 
		"Arschlocke", 
		"Ashley", 
		"Aso", 
		"Atomspast", 
		"Auspuffbumser", 
		"Bachel", 
		"Badkapp", 
		"bangen", 
		"Berber", 
		"Besen", 
		"Blödfisch", 
		"Blödmusiker", 
		"Bodendompteuse", 
		"Brunskuh", 
		"Buckelhur", 
		"Bumsnuss", 
		"Buschmensch", 
		"Butterkuh", 
		"Cholerator", 
		"Computerflüsterer", 
		"Dauerlutscher", 
		"Dollbohrer", 
		"Donnerfotze", 
		"Doofmannsgehilfe", 
		"Doppeldepp", 
		"Dreilochnutte", 
		"Du Ast!", 
		"Dumm-Rasseler", 
		"Dünnschissgurgler", 
		"Eibemme", 
		"Eichelarschkopf", 
		"Farnhoune", 
		"Fäkalterrier", 
		"FDM", 
		"Fitch", 
		"Flachgeist", 
		"Flattermuschi",
		"Flodder",
		"Fontanellenfick",
		"Fotze",
		"Gargamel",
		"Gaylon",
		"Gebärfrau",
		"Geburtsfehlermiss",
		"geistiger Tiefflieger",
		"Gesichtseintopf",
		"Gesichtsmorph",
		"Gnarf",
		"Gnogel",
		"Grasdackel",
		"Gratler",
		"Großhirnkastrat",
		"H2O-Kopf",
		"Hack ab!",
		"Hackfresse",
		"Halbaffe",
		"Hannefatzke",
		"hartzig",
		"Hausschuhgesicht",
		"hirnamputierter Rhinozerusarsch",
		"Hodenbussard",
		"Hodenkopf",
		"Hodenschrubbler",
		"Hohlbratze",
		"hohle Fritte",
		"Honk",
		"Hosenlottle",
		"Hosentaschen Godzilla",
		"HRSN",
		"Huru",
		"Hutze",
		"Hübi",
		"ins Hirn scheißen",
		"Intelligenzverweigerer",
		"Kackbatzen",
		"Kackstuhl",
		"Kanisterkopf",
		"Klapskalli",
		"Klitzmorchel",
		"Klufenmichel",
		"Knallarsch",
		"Kotlutscher",
		"Kotzkannenfressbrett",
		"Kotzkrücke",
		"Krapfengesicht",
		"Larve",
		"Lattenheinrich",
		"Lattenschreck",
		"Lällebäbbl",
		"Liam",
		"Loser",
		"mangelbegent",
		"Missi",
		"Mongo",
		"Mr. Grotte",
		"Muschischeps",
		"Nafti",
		"Napfwurst",
		"Nougatnutte",
		"Nuddebumber",
		"Orgasmusbremse",
		"oshig",
		"Otzenfrosch",
		"Paragrafenschubse",
		"Partyopfer",
		"Paselacke",
		"Peniskopf",
		"Penisprothesenträger",
		"Pfeifenheini",
		"Pferdefresse",
		"Pfingstochse",
		"pickelgesichtiger Spritzbock",
		"Pimmel",
		"Pimmelkopf",
		"Pimmelpapagei",
		"Pisskajole",
		"Plempe",
		"Pleppo",
		"Pottmolch",
		"Sackfotze",
		"Sch Lampe",
		"Schlabberlappen",
		"schleimscheißender Bambusaffe",
		"Schmalzgrab",
		"Schmalztitte",
		"Schmongo",
		"Schmönkchen",
		"Schmudel",
		"schnarchzapfiger Rüsselsack",
		"Schüttler",
		"Senfgurke",
		"Sheamus",
		"Simbel",
		"Spaltenspengler",
		"Spammailautor",
		"Spastard",
		"Spoastie",
		"Spongebob",
		"Sponk",
		"Staubbeutel",
		"Steroidbeule",
		"Steroidmutant",
		"Tapetengerippe",
		"Topmoppel",
		"Tüffel",
		"Unwerk",
		"Vollaffe",
		"vollgepisste Strumpfhose",
		"vollgeschissene Menschenhülle",
		"Vollmongo",
		"Vongo",
		"Wachsfresse",
		"Waldwichtel",
		"Wichsbazille",
		"Wichsfisch",
		"Wikidiot",
		"Wulfer",
		"wulffen",
		"Zahnspangenbettler",
		"zoologisches Abfallprodukt",
		"Armleuchter",
		"Arsch",
		"Arschgeige",
		"Arschloch",
		"Ausrangierte Klapperschlange",
		"Draufgehen",
		"Dreckskerl",
		"Du kannst mich mal am Arsch lecken!",
		"Fick dich ins Knie!",
		"Fick dich!",
		"Geil",
		"Heiliger Bimbam!",
		"Hurensohn",
		"Kacke",
		"Krepieren",
		"Nervensäge",
		"Nutte",
		"Obertussi",
		"Sau",
		"Sauhund",
		"Schande",
		"Scheisse",
		"Schlampe",
		"Schwein",
		"Verdammt",
		"Verrecken",
		"Wixer",
		"Ass",
		"Asshole ",
		"Bastard ",
		"Bitch ",
		"Blast ",
		"Bloody hell ",
		"Bloody thing ",
		"Bollocks ",
		"Bugger me!",
		"Bullshit ",
		"Crap ",
		"Damn ",
		"Fool ",
		"Fuck ",
		"Fuck off! ",
		"Go to hell! ",
		"He’s a real dickhead ",
		"He’s a real shit ",
		"He’s a stupid prick ",
		"He’s a total wanker",
		"He’s an arsehole ",
		"Hell ",
		"I don’t give a shit!",
		"Idiot ",
		"It was bloody awful ",
		"It was really crap ",
		"Like hell I will! ",
		"Load of shit",
		"Looser ",
		"Motherfucker ",
		"Piss off ",
		"Shit ",
		"To be up shit creek",
		"Wanker",
		"You stupid sod!",
		"Asino",
		"Bastardo ",
		"Bruto figlio della mignotta",
		"Brutto",
		"Cacca",
		"Cavolo ",
		"Cazzo ",
		"Che me ne fregha! ",
		"Coglione ",
		"Cornuto ",
		"Cretino ",
		"Diavolo",
		"Figlio di puttana",
		"Idiota",
		"Imbecillo ",
		"Incubi",
		"Ma vaffangulo!",
		"Maiale",
		"Maledetta",
		"Maledizione ",
		"Manicomio ",
		"Mannaggia la miseria ",
		"Mannaggia",
		"Merda",
		"Mostro",
		"Pazzo",
		"Piccoli brividi",
		"Sei come un pupazzo parlante",
		"Puzzolo",
		"Rompere i coglioni",
		"Rompi scatole ",
		"Scemo ",
		"Scimmia",
		"Spavantapassero",
		"Stregha",
		"Stronzo",
		"Stupidaccine ",
		"Stupido ",
		"Terribile",
		"Vacca la miseria",
		"Bordel",
		"C’est dégueulasse ",
		"Casse-toi!",
		"Connard",
		"Connasse",
		"Crétin",
		"Espèche d’enculé",
		"Ferme-la!",
		"Je m’en fous!",
		"Merde",
		"Putain de merde",
		"Quel con!",
		"Quelle saloperie",
		"Sale chien",
		"Sale con",
		"Ta gueule!",
		"Tire-toi! ",
		"Tu m’emmerdes!",
		"Va te foutre ",
		"Zut!",
		"ääliö ",
		"Äitisi nai poroja ",
		"älykääpiö ",
		"Anna persettä ",
		"Anna vittua ",
		"Äpärä ",
		"Fägäri ",
		"Fägis ",
		"Haahka ",
		"Haista paska ",
		"Haista vittu ",
		"Haista vittu! ",
		"Harrastaa seksiä ",
		"Heitä homo voltti! ",
		"Helvetti ",
		"Hemmetti ",
		"Herpesperse ",
		"Hevon vittu ",
		"Hevonvitun perse ",
		"Hinaaja ",
		"Hintti ",
		"Hinuri ",
		"Hitto ",
		"Homo ",
		"Homoperse",
		"Homppeli ",
		"Horatsu ",
		"Horo (Huora) ",
		"Huoranpenikka ",
		"Huoranperse ",
		"Huoripukki ",
		"Hypää kaivoon ",
		"Ime kyrpää ",
		"Ime mun muna lutka! ",
		"Ime paskaa ",
		"Inva ",
		"Istun taikka kävelen, perä antaa sävelen",
		"Jälkeiset",
		"Jälkiliukkaat ",
		"Jeesuskyrpä ",
		"Jos olisin noin ruma, kusisin muuntajaan! ",
		"Jumalauta ",
		"Juntti ",
		"Juokse junan alle!",
		"Juoppo ",
		"Kaappihomo ",
		"Karvakolmio ",
		"Katiska",
		"Kerro äidillesi, että maksan myöhemmin ",
		"Kettutyttö ",
		"Kives ",
		"Kolmannen asteen turbomuna ",
		"Kristuksen vittu ",
		"Kullin lutkuttaja ",
		"Kuohilas ",
		"Kuraperse ",
		"Kurapillu ",
		"Kuse muuntajaan! ",
		"Kusiainen ",
		"Kusiaivo ",
		"Kusipää ",
		"Kusiparta ",
		"Kusiperse ",
		"Kyrpä ",
		"Kyrpäjyrä ",
		"Kyrvänsyylä ",
		"Laardiperse ",
		"Läski, tankki,paksu ",
		"Läskiperse ",
		"Lättäperse",
		"Limavittu ",
		"Lintumies ",
		"Loskavittu ",
		"Lutku ",
		"Masturboida ",
		"Mene jouseen ",
		"Mitä vittua?! ",
		"Mulkku",
		"Mulkvisti ",
		"Mutsinnussija",
		"Naida ",
		"Nännipihan talonmies ",
		"Narkkari ",
		"Narttu ",
		"Nisti ",
		"Nörtti ",
		"Nuija ",
		"Nukkepöksy ",
		"Nussia ",
		"Onko sinun naamaasi ammuttu haulikolla? ",
		"Ota pikkuhousut pois ja pyllistä, lutka ",
		"Otat kuulemma perseeseen mielelläsi ",
		"Päässäsi tekee paska patoja ja kusi puroja ",
		"Painu helvettiin ",
		"Painu vittuun ",
		"Palli ",
		"Pallinaama ",
		"Panopuu ",
		"Paras osa sinusta valui lihavan äitisi sisäreittä pitkin ",
		"Paska ",
		"Paskaa käteen! ",
		"Paskaa paahtoleivällä! ",
		"Paskanaama ",
		"Paskanmarjat ",
		"Paskapää ",
		"Paskavatsa ",
		"Paskiainen ",
		"Pässi ",
		"Pelle ",
		"Peppu ",
		"Peräkammarinpoika ",
		"Perkele ",
		"Perse ",
		"Perseen nuolija ",
		"Perseensuti ",
		"Persereikä ",
		"Persikkapylly ",
		"Pikkupillu ",
		"Pillu ",
		"Pimppi ",
		"Pissaliisa ",
		"Pöljä",
		"Pompo ",
		"Pottupillu ",
		"Puhkon silmäsi ja kusen aivoihisi, senkin paskanaama hinttari! ",
		"Pulsu ",
		"Pulunnussija ",
		"Pyöriä kuin puolukka pillussa ",
		"Rakastella ",
		"Räpätäti, humppatäti ",
		"Rekkamiehen pastilli ",
		"Revi persees ",
		"Revin perseesi irti ja syötän sen sinulle ",
		"Ruma huoranraiskaaja ",
		"Runkata ",
		"Runkkari ",
		"Ruskean reiän ritari ",
		"Ruumiinraiskaaja ",
		"Saatana ",
		"Saatanan äpärä ",
		"Saatanan Kakarat ",
		"Saatanan sarjarunkkaaja ",
		"Saatanan sika ",
		"Selluperse ",
		"Sellusääri ",
		"Separi ",
		"Severi ",
		"Sinä imet löysää muna ",
		"Sinä olet paskapää ",
		"Sissijuusto ",
		"Skeida ",
		"Skitso ",
		"Slerssi ",
		"Spuge ",
		"Spurgu ",
		"Suksi vittuun ",
		"Suolijuna ",
		"Sutenööri ",
		"Syö paskaa ",
		"Tampio ",
		"Tanopää",
		"Tätisetä",
		"Teinipimppi",
		"Tissit ",
		"Tuhero ",
		"Tuhkamuna ",
		"Tulee puukosta! ",
		"Tumputtaa ",
		"Tussu ",
		"Urpo/ jurpo ",
		"Vajokki ",
		"Vedä ittes hirteen ",
		"Vedä käteen",
		"Du Alltagsherd",
		"Du Biografieverzierer",
		"Du Blutbluse",
		"Du Blutkuchen",
		"DU Blutwurstdecke",
		"Du Brunftkralle",
		"Du Deutschlautsprecher",
		"Du Dudelhintern",
		"Du Einweg-Hilfsschwester",
		"Du Fleischzapfen",
		"Du Frankensteinprodukt",
		"Du frauenlose Verwahrlosung",
		"Du Fresskommando",
		"Du Gebeinzerfall",
		"Du Gedankenwalzwerk",
		"Du Gedichtwürstel",
		"Du Gefrierpolster",
		"Du Gehirnbindung",
		"Du Geistestraktor",
		"Du Geschlechtsgewächs",
		"Du Geschlechtsmelkerin",
		"Du Geschlechtsnothelfer",
		"Du Giftlimonade",
		"Du Gurgelhaut",
		"Du Haardach",
		"Du Hirnmayonnaise",
		"Du Hundestrahl",
		"Du Innengeschwulst",
		"Du Jagdschauer",
		"Du Jungbomber",
		"Du Kadavertrümmer",
		"Du Karrentier",
		"Du Katholikennadel",
		"Du Klobenstiefel",
		"Du Knochenbrecherin",
		"Du Kunsterdbeben",
		"Du Latexagglutinationstest",
		"Du Latrinenland",
		"Du Lebenskäse",
		"Du Leibskuchen",
		"Du Leibstopf",
		"Du Leichenkrümel",
		"Du Liane vollblondlicher Verblödung",
		"Du Mammarchie ",
		"Du Mannshahn",
		"Du Menschenstrunk",
		"Du mottenhafter Zwischenbereichston",
		"Du Naturkanal",
		"Du Nirgendsgesicht",
		"Du Plastikkeks",
		"Du Regierungsmuskel",
		"Du Rustikalgarderobe ",
		"Du Sachspendefabrik ",
		"Du Saftloch",
		"Du Salatfrisur",
		"Du Schicksalsbundstiefel",
		"Du Schistallgedanke",
		"Du Schlummerkeule",
		"Du Selbstzeitlose",
		"Du Spielschun",
		"Du Steinschmelzerin",
		"Du Tochtergeschwulst",
		"Du Tochterwesen",
		"Du Tortenpeitsche",
		"Du Tötungsstiefel",
		"Du Trachtenbein",
		"Du Verdauungstruhe",
		"Du warme Gefühlskotsäule",
		"Du weisses Parasitenmehl der Übergangenen",
		"Du windschiefes Urteil",
		"Du Wirklichkeitsparkplatz",
		"Du Wolkenpotpourri",
		"Du Wühlbank",
		"Du Zusammennatur",
		"Lutschei",
		"Schmockenteufel",
		"Schlafwagenschaffner",
		"A-Klasse-nicht-zum-Kippen-Bringer",
		"schwuler Messdiener",
		"Analfrosch",
		"Hühnerficker",
		"Sohn einer blutpissenden Hafenhure ",
		"Gabbafotze",
		"Evolutionsbremse ",
		"Karussellbremser",
		"Teflongesicht ",
		"Homo-Fürst der Finsternis",
		"Pappnase",
		"Kabelklemme",
		"Hammerwerfer",
		"Windbeutel",
		"Klappstuhl",
		"Fäkalgesicht",
		"Knetmännchen",
		"Oberfranke",
		"(nasser) Lappen",
		"Futzpipe",
		"Protesenzar",
		"Pausenkiffer",
		"Haubentaucher",
		"Fickschlitz",
		"Sumpfschnepfe",
		"Schweinepriester",
		"Schnieptröte",
		"rasende Wildsau",
		"Hochdruckschädel",
		"Amiga-Hirn",
		"Bettnässer",
		"Maraggeldaggel",
		"Flitzpupe",
		"Erbsenzähler",
		"Joghurtbecher",
		"Rentnerschwemme",
		"Handlampe",
		"Arschprolet",
		"Sackgesicht",
		"Korkenzieher",
		"Miss Türkei",
		"Furunkel",
		"Kolbenfresser",
		"Wettkampfstinker",
		"Turnbeutel",
		"Kotgebäck von Goul",
		"Hurensohn",
		"Quastenflosser",
		"Eiterbeule",
		"Gesichtsfotze",
		"Schlampen-mehrmal-Ficker",
		"Vagina",
		"Arschgeburt",
		"Pimperperle",
		"Am-Sperma-Riecher",
		"Afterlecker",
		"Kackfass",
		"Hackfresse",
		"Hungerlatte",
		"Feierabendpolitiker",
		"Weihnachtsblödmann",
		"Notleuchte",
		"Kuhmagen",
		"Wasserträger",
		"Zecke",
		"Schmierwurst",
		"Seifenspender",
		"Trauerweide",
		"Heulboje",
		"Flötenkönig",
		"Jammersack",
		"Ersatzteil",
		"Schießbudenfigur",
		"Warmduscher",
		"Pupenknutscher",
		"Blindflansch",
		"Klofinger",
		"Koppelschaf",
		"Fliegenfurz",
		"Pillemann-Sack-Fresse",
		"Primat",
		"Schwachstruller",
		"Schurke",
		"Abschenker",
		"Klappspaten",
		"Wuchtbrumme",
		"Blödmannsgehilfe",
		"Hasenhirn",
		"Eiermaler",
		"Gipskopf",
		"Scheisshausdeckel",
		"Einzeller",
		"Bremser",
		"Querulant",
		"Spasti",
		"Stricher",
		"Bratarsch",
		"Masturbant",
		"schwuler Messdiener",
		"Mastdarmakrobat",
		"Feierabendclown",
		"Pissbacke",
		"Friedhofsjodler",
		"Weichei",
		"Pausenclown",
		"Muffensack",
		"Geizknochen",
		"Kiftenkriecher",
		"Leberwurstbrot",
		"Platzbuttergesicht",
		"Salami",
		"Arschgutzi",
		"Gurkenschäler",
		"Clearasilversuchsgelände",
		"Doppel-Null-Agent",
		"Muellbeutelimitat",
		"Bloedspaten",
		"Dumpfmuffe",
		"Pansen",
		"Schorfkopf",
		"Bewegungslegasteniker",
		"Gesichtssieben",
		"Gipsnacken",
		"Medikamententester",
		"Dünnstrahlpisser",
		"Drecksschüppengesicht",
		"Baumschüler",
		"Furzfänger",
		"Hirnamputierter",
		"Brüllarsch",
		"Geschnack",
		"Spaßbremse",
		"Scheinasylant",
		"Saftschlepper",
		"Arschnase mit Analantrieb",
		"Klotzkopp",
		"Schwanzlurch",
		"Kotzfresse",
		"Subjektil",
		"Pinocchioverschnitt",
		"Furzdüse",
		"Blaupause",
		"Stümper",
		"Auspufflutscher",
		"Bananenbieger",
		"Trittbrettfahrer",
		"Fehlgeburt",
		"Hilfsschüler",
		"Scheißhaufen",
		"Eierfeile",
		"Dumpfbacke",
		"Schmeissfliege",
		"Linksabbieger",
		"Sonderschulschwänzer",
		"Toilettengesicht",
		"Kloschüssel",
		"Pißnudel",
		"Dünnbrettbohrer",
		"Fliegenfänger",
		"Sackwalze",
		"Handtuchhalter",
		"Kotspender",
		"Beulengesicht",
		"Gesichts-Günther",
		"Schlapp-Ursel",
		"Gehirnakrobat",
		"Wurstfinger",
		"Kackfass",
		"Bückstück",
		"Schamhaarschädel",
		"Pimmelbär",
		"Abspritzer",
		"Nachgeburt",
		"Genitaldenker",
		"Proteinsack",
		"Suppenbärbel",
		"Aushilfsamöbe",
		"Dönergesicht",
		"Fotze 86",
		"Arschloch",
		"Hackfresse",
		"Griesnockerlgesicht",
		"Dönergesicht",
		"Dummschüler",
		"Napfspucker",
		"Rübengesicht",
		"Lufthutzen",
		"Schwachstromfunker",
		"Dorftrottel",
		"Schwulette",
		"Biobauer",
		"schwuler Klarinettenspieler",
		"Spinatwachtel",
		"Plastekasper",
		"Kotklumpen",
		"Gesichtseimer",
		"Saftnase",
		"Strauchklopper",
		"Hafensänger",
		"Klippenspringer",
		"Bahnhofsgeiger",
		"Vollfriseur",
		"Schwammhorn",
		"Schwabbelpanzer",
		"Analintruder",
		"genetischer Abfall",
		"Mehlauge",
		"Spacken",
		"Strichmännchen",
		"Gebärmutterauswuchs",
		"Stammtischprophet",
		"Nasenbär",
		"Kackfrosch",
		"Löffelhirsch",
		"Gesichtspilz",
		"Pissflitsche",
		"Suppengesicht",
		"Eierkocher",
		"Gurkenlurch",
		"Breitarschantilope",
		"Tomatenschäler",
		"Honigschimmel",
		"Ölschnepfe",
		"Email-Softi",
		"Knor-Auflauf",
		"Bitch",
		"Hodenkobolt",
		"Fotzenkäse",
		"Rechtschreibüberprüfungsprogrammbenutzer",
		"Pimmelflöte",
		"Kotnascher",
		"Arschwabe",
		"Wechselfestplatte",
		"Körpergünther",
		"Nebelkrähe",
		"Krampfaderngeschwader",
		"Tropenvogel",
		"Sandmann",
		"Statist",
		"Milchschnitte",
		"sezilianischer Zementmischer",
		"Pansenfresse",
		"Muhhorn",
		"Spaghettisultan",
		"Dummtröte",
		"Bückstück",
		"Halbgewalkter",
		"Krustenbraten",
		"Schneesieber",
		"Blindstopfen",
		"Ziegenschänder",
		"Eichelzyste",
		"Quotenschnecke",
		"Spreitzfuß",
		"Pillemann",
		"Gesichtseintopf",
		"Knallfrosch",
		"Schamhaarzucht",
		"Prollkopp",
		"Muttersöhnchen",
		"Strumpfhalter",
		"Lackaffe",
		"Dosenbierbaracke",
		"Schmalspurrambo",
		"Halunke",
		"Höllenhund",
		"Kotecke",
		"Schluchtenkacker",
		"Ohrfeigengesicht",
		"Sandkastenrocker",
		"Pilzwarze",
		"Knabberleiste",
		"Gesichtselfmeter",
		"Ackerfresse",
		"Klobrille",
		"Rosettenkönig",
		"Steckdosenbefruchter",
		"Monsterbacke",
		"Spermarutsche",
		"Schleim-scheissende-Bambus-Kröte",
		"Laternenschlampe ",
		"Hurensohn",
		"Bumsklumpen",
		"Blödföhn",
		"Wixxer",
		"Wixxxxer",
		"Wixxxxxxer",
		"Wixer",
		"Pisser",
		"Piser",
		"Pissnelke",
		"Bastard",
		"Kanacke",
		"Kanake",
		
	}
end

-- EVENT HANDLER --

ChatBoxServer:New();

		
		